### ISSUE TITLE
Trying to require react-draggable. Browserify exited with code 1. It can't find react.

### ISSUE THREAD

**Issue by im-martijn** [jfhbrook/wzrd.in#152]
Hi,

I wanted to try `react-draggable` on requirebin.com. It doesn't work. I opened an [issue on the react-draggable github page](https://github.com/mzabriskie/react-draggable/issues/210), but I'm not sure if the error is with them, with the cdn or with my code.

The issue I mentioned above contains the html and js code I used in requirebin and the error message I got.

Should I change something in my code? Should react-draggable change something to make this work? Should something be changed in the cdn? I don't know.

Any thoughts?

Best regards,
Martijn Senden

**Comment by jfhbrook** [comment]
A lot of react shit breaks because wzrd.in doesn't support peer dependencies\*. Probably what's going on here. See: #130 

\* It *could*, with a huge refactor and a new API endpoint, but this would require sorting out some backed up merges/deploys (see: #133 ) and also sweeping changes to requirebin.com (which I don't have any control over). So good luck. :)

**Comment by im-martijn** [comment]
Thanks. Will just make a gist locally. ;-)
