### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by gpspake** [jfhbrook/wzrd.in#157]
https://wzrd.in/ has been down for most of the day, it seems.
See also #156

**Comment by jfhbrook** [comment]
I will not be able to look at this until I'm home. This will be in roughly 5 hours. It's most likely an issue of disk space--I was able to help this a little by removing logs yesterday, but I think the cache might be too big now. @maxogden pinging you for visibility--if you can look at this before I get home great, otherwise there's a good chance I'm gonna just nuke the cache and restart and, well, the service will just fall over for a while and that's how it is.

**Comment by ErwanLent** [comment]
+1

**Comment by jfhbrook** [comment]
Implemented the cache nuke. Site is up, cache is frigid. Good luck!

**Comment by jfhbrook** [comment]
Also decreased the cache TTL to hopefully avoid this in the future.
