### ISSUE TITLE
It seems that the SSL cert has expired

### ISSUE THREAD

**Issue by dxr27kejj** [jfhbrook/wzrd.in#173]
https://www.sslshopper.com/ssl-checker.html#hostname=wzrd.in

#147

I'm getting "Error: CORS request rejected: https://wzrd.in/multi" error on esnextb.in

@jfhbrook @voronianski

**Comment by IllyaMoskvin** [comment]
Seconded. Chrome says `NET::ERR_CERT_DATE_INVALID`

Looks like the site was secured with Let's Encrypt, so you should be able to set up a cron job to renew it automatically. Assuming that the `certbot-auto` script is inside the home directory of whatever system user account is responsible for administering the website, try running:

```
~/certbot-auto renew
```

...and if that works, I _think_ adding this cron job to that user should take care of it:

```
0   0   1   *   *   ~/certbot-auto renew --quiet --no-self-upgrade > /dev/null 2>&1
```

That should try to renew the cert at midnight on the first day of every month.

It's been a while since I've set up Let's Encrypt, so I might have gotten some details wrong.

**Comment by IllyaMoskvin** [comment]
In the meantime, if you are pressed for development time, here's how you download whatever script's breaking your page:

```
curl -k https://wzrd.in/standalone/change-case@latest > change-case.js
```

The `-k` (or `--insecure`) option will ignore certificate errors.

**Comment by jfhbrook** [comment]
There's already a cron job, it's just apparently broken.

this happened at a really bad time because I just went through a disk failure and I have a fever at the same time...so going to be a bit before I can dig in even assuming I can recover the SSH key.

**Comment by jfhbrook** [comment]
My fever broke, my parts got here, DR went smoothly, and I was able to manually run the certbot renewal and try a minor adjustment to see if that helps the cron job run better.

Apologies for the inconvenience.
